server:
  test: http://127.0.0.1:8888/
  dev: http://www.layercake.com.cn/

# 基准的请求头信息
request_headers:
  Accept-Encoding: gzip, deflate, br
  Accept-Language: zh-CN,zh;q=0.9
  User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36
  Content-Type: application/json


# 提取规则设置
expr:
  # 提取token的jsonpath表达式
  token: $.result.token

file_path:
  test_case: ../data/case_data1.xlsx
  report: ../report/
  log: ../log/run{time}.log

email:
  # 发件人邮箱
  user:  123456.com
  # 发件人邮箱授权码
  password:  ASGCSFSGS
  # 邮箱host
  host:  smtp.163.com
  contents:  解压apiAutoReport.zip(接口测试报告)后，请使用已安装Live Server 插件的VsCode，打开解压目录下的index.html查看报告
  # 收件人邮箱
  addressees:  ["收件人邮箱1","收件人邮箱2","收件人邮箱3"]
  title:  接口自动化测试报告(见附件)

